### /car/carToCarDto
GET http://localhost:14011/car/carToCarDto?make=a&numberOfSeats=10&carType.name=ct&carType.category=c

### /car/comp/carToCarDto
GET http://localhost:14011/car/comp/carToCarDto?make=a&numberOfSeats=10&carType.name=ct&carType.category=c
